name: "Verify Remote Git Refs Equality"
description: >
  Enhance your repository mirroring process with this GitHub Action.
  It ensures that the references (refs) in your remote Git repositories are identical,
  preventing unnecessary clone-push cycles.
  Keep your mirrors up-to-date and synchronized efficiently.
author: "Jan Chren ~rindeal"

inputs:
  'source-repo-url':
    description: "The URL of the source Git repository"
    required: true
  'target-repo-url':
    description: "The URL of the target Git repository"
    required: true

outputs:
  'refs-differ':
    description: "Indicates if the repositories have different references (true/false)"
  'diff-message':
    description: "Details the differences found between repositories (if any)"
  'diff-type':
    description: "Type ID categorizing the difference (if any)"
  'source-repo-url':
    description: "URL of the source Git repository (same as input)"
  'target-repo-url':
    description: "URL of the target Git repository (same as input)"

runs:
  using: 'node20'
  main: 'dist/index.js'
