name: "Smoke Test"

on:
  push:
    branches:
      - 'master'
    paths:
      - ".github/workflows/smoke-test.yml"
  pull_request:
  workflow_dispatch:

# outputs:
#   'refs-differ':
#     description: "Boolean indicating if the repositories are different"
#   'diff-message':
#     description: "Optional message describing the differences"
#   'diff-type':
#     description: "Optional type of the difference"
#   'source-repo-url':
#     description: "URL of the source Git repository"
#   'target-repo-url':
#     description: "URL of the target Git repository"

jobs:
  'smoke-test':
    runs-on: 'ubuntu-latest'

    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        'json':
          - |
            {
              "testName": "Test source(github.repository), target(github.repository)",
              "expectedRefsDiffer": false,
              "sourceRepoUrl": ${{ toJSON(format('https://github.com/{0}.git', github.repository)) }},
              "targetRepoUrl": ${{ toJSON(format('https://github.com/{0}.git', github.repository)) }}
            }
          - |
            {
              "testName": "Test Source Repo Equals Mirror Repo",
              "expectedRefsDiffer": false,
              "sourceRepoUrl": "https://git.launchpad.net/beautifulsoup",
              "targetRepoUrl": "https://github.com/facsimiles/beautifulsoup.git"
            }

    name: >
      Test ${{ fromJSON(matrix['json'])['testName'] }}

    steps:
      - name: "Dump Matrix JSON"
        shell: bash -euo pipefail {0}
        run: |
          echo "${MATRIX_JSON}" | jq -c .
        env:
          'MATRIX_JSON': ${{ matrix['json'] }}

      - name: "Checkout current repository"
        uses: 'actions/checkout@main'

      - name: >
          Test ${{ fromJSON(matrix['json'])['testName'] }}
        id: 'test'
        uses: './'
        with:
          'source-repo-url': ${{ fromJSON(matrix['json'])['sourceRepoUrl'] }}
          'target-repo-url': ${{ fromJSON(matrix['json'])['targetRepoUrl'] }}

      - name: >
          Assert ${{ fromJSON(matrix['json'])['testName'] }}
        uses: 'actions/github-script@main'
        with:
          script: |
            const assert = require('node:assert/strict')

            const steps = JSON.parse(process.env['STEPS'])
            const prevStepOutputs = steps[Object.keys(steps).pop()].outputs

            const matrix = JSON.parse(process.env['MATRIX_JSON'])

            core.summary.addHeading(matrix["testName"], 2)
            core.summary.addCodeBlock(JSON.stringify(prevStepOutputs, null, "  "), 'json')
            
            console.log({refsDiffer: prevStepOutputs['refs-differ']})
            const refsDiffer = JSON.parse(prevStepOutputs['refs-differ'])
            assert.strictEqual(typeof refsDiffer, 'boolean')
            assert.strictEqual(refsDiffer, matrix["expectedRefsDiffer"])

            assert.strictEqual(prevStepOutputs['source-repo-url'], matrix["sourceRepoUrl"])
            assert.strictEqual(prevStepOutputs['target-repo-url'], matrix["targetRepoUrl"])
            
            core.summary.write()
        env:
          'STEPS': ${{ toJSON(steps) }}
          'MATRIX_JSON': ${{ matrix['json'] }}

      # - name: "Test Source Repo Equals Mirror Repo"
      #   id: 'test-source-equals-mirror'
      #   uses: './'
      #   with:
      #     'source-repo-url': 'https://git.launchpad.net/beautifulsoup'
      #     'target-repo-url': 'https://github.com/facsimiles/beautifulsoup.git'

      # - name: "Assert Source Repo Equals Mirror Repo"
      #   uses: 'actions/github-script@main'
      #   with:
      #     script: |
      #       const assert = require('node:assert/strict')

      #       const steps = JSON.parse(process.env['STEPS'])
      #       const prevStepOutputs = steps[Object.keys(steps).pop()].outputs

      #       core.summary.addHeading(Object.keys(steps).pop(), 2)
      #       core.summary.addCodeBlock(JSON.stringify(prevStepOutputs, null, "  "), 'json')

      #       const refsDiffer = JSON.parse(prevStepOutputs['refs-differ'])
      #       assert.strictEqual(refsDiffer, false)
            
      #       core.summary.write()
      #   env:
      #     'STEPS': ${{ toJSON(steps) }}


      # - name: Run local action with different URLs that should differ
      #   id: test_different_repos
      #   uses: ./
      #   with:
      #     source-repo-url: ${{ github.repository }}
      #     target-repo-url: 'https://github.com/rindeal-js/git-remote-ref-compare.git'

      # - name: Output results
      #   run: |
      #     echo "Current repo vs current repo: ${{ steps.test_current_repo.outputs.refs-differ }}"
      #     echo "Equal repos: ${{ steps.test_equal_repos.outputs.refs-differ }}"
      #     echo "Different repos: ${{ steps.test_different_repos.outputs.refs-differ }}"
      #   env:
      #     INPUT_REFS_DIFFER_OUTPUTS: ${{ toJSON(steps.test_current_repo.outputs) }}
