name: "Smoke Test"

on:
  push:
    branches:
      - 'master'
    paths:
      - ".github/workflows/smoke-test.yml"
  pull_request:
  workflow_dispatch:

jobs:
  'smoke-test':
    runs-on: 'ubuntu-latest'

    steps:
      - name: "Checkout current repository"
        uses: 'actions/checkout@main'

# outputs:
#   'refs-differ':
#     description: "Boolean indicating if the repositories are different"
#   'diff-message':
#     description: "Optional message describing the differences"
#   'diff-type':
#     description: "Optional type of the difference"
#   'source-repo-url':
#     description: "URL of the source Git repository"
#   'target-repo-url':
#     description: "URL of the target Git repository"

      - name: "Set Vars"
        id: 'vars'
        uses: 'actions/github-script@main'
        with:
          script: |
            const { githubRepository } = process.env
            if ( ! githubRepository ) throw new Error()
            core.setOutput('githubRepositoryHttpsUrl', `https://github.com/${githubRepository}`)
        env:
          'githubRepository': ${{ github.repository }}


      - name: "Test source(github.repository), target(github.repository)"
        id: 'test-current-repo'
        uses: './'
        with:
          'source-repo-url': "${{ steps['vars'].outputs['githubRepositoryHttpsUrl'] }}"
          'target-repo-url': "${{ steps['vars'].outputs['githubRepositoryHttpsUrl'] }}"

      - name: "Assert `refs(github.repository) === refs(github.repository)`"
        uses: 'actions/github-script@main'
        with:
          script: |
            const assert = require('node:assert/strict')

            const steps = JSON.parse(process.env['STEPS'])
            const prevStepOutputs = steps[Object.keys(steps).pop()].outputs

            core.summary.addHeading(Object.keys(steps).pop(), 2)
            core.summary.addCodeBlock(JSON.stringify({prevStepOutputs}, null, "  "), 'json')
            
            console.log({refsDiffer: prevStepOutputs['refs-differ']})
            const refsDiffer = JSON.parse(prevStepOutputs['refs-differ'])
            assert.strictEqual(typeof refsDiffer, 'boolean')
            assert.strictEqual(refsDiffer, false)

            // const githubRepositoryHttpsUrl = "${{ format('https://github.com/{0}', github.repository) }}"
            const githubRepositoryHttpsUrl = steps['vars'].outputs['githubRepositoryHttpsUrl']
            assert.strictEqual(prevStepOutputs['source-repo-url'], githubRepositoryHttpsUrl)
            assert.strictEqual(prevStepOutputs['target-repo-url'], githubRepositoryHttpsUrl)
            
            core.summary.write()
        env:
          'STEPS':   ${{ toJSON(steps) }}

      - name: "Test Source Repo Equals Mirror Repo"
        id: 'test-source-equals-mirror'
        uses: './'
        with:
          'source-repo-url': 'https://git.launchpad.net/beautifulsoup'
          'target-repo-url': 'https://github.com/facsimiles/beautifulsoup.git'

      - name: "Assert Source Repo Equals Mirror Repo"
        uses: 'actions/github-script@main'
        with:
          script: |
            const assert = require('node:assert/strict')

            const outputs = JSON.parse(process.env['OUTPUTS'])
            const prevStepOutputs = outputs[Object.keys(outputs).pop()]

            core.summary.addCodeBlock(JSON.stringify({prevStepOutputs}, null, "  "), 'json')

            const refsDiffer = JSON.parse(prevStepOutputs['refs-differ'])
            assert.strictEqual(refsDiffer, false)
            
            core.summary.write()
        env:
          'OUTPUTS': ${{ toJSON(steps.*.outputs) }}


      # - name: Run local action with different URLs that should differ
      #   id: test_different_repos
      #   uses: ./
      #   with:
      #     source-repo-url: ${{ github.repository }}
      #     target-repo-url: 'https://github.com/rindeal-js/git-remote-ref-compare.git'

      # - name: Output results
      #   run: |
      #     echo "Current repo vs current repo: ${{ steps.test_current_repo.outputs.refs-differ }}"
      #     echo "Equal repos: ${{ steps.test_equal_repos.outputs.refs-differ }}"
      #     echo "Different repos: ${{ steps.test_different_repos.outputs.refs-differ }}"
      #   env:
      #     INPUT_REFS_DIFFER_OUTPUTS: ${{ toJSON(steps.test_current_repo.outputs) }}
